version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: kadince_todo_api_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/kadince_todo_api_development
      # RAILS_MASTER_KEY: 
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    command: >
      bash -c "
        bundle install &&
        ./bin/rails db:prepare &&
        ./bin/rails server -b 0.0.0.0 -p 3000
      "

volumes:
  postgres_data:
  bundle_cache:
