version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      BUNDLE_DEPLOYMENT: "0"
      BUNDLE_WITHOUT: ""
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    command: >
      bash -c "
        bundle install &&
        ./bin/rails db:prepare &&
        ./bin/rails server -b 0.0.0.0 -p 3000
      "
    ports:
      - "3000:3000"

volumes:
  node_modules:
